version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/var/www/html:cached
    working_dir: /var/www/html  # Add this line
    ports:
      - "8000:80"

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
      - "3307:3306"
  
volumes:
  mariadb-data: {}
